[package]
name = "volumetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "volumetrics"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
numpy = "0.19.0"
pyo3 = "0.19.0"